version: '3'
volumes:
  data:
services:
  postgres:
    container_name: postgres_db
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  minio:
    container_name: minio_storage
    image: quay.io/minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
